# Generated by Django 5.1.2 on 2024-10-22 21:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_user_managers_user_security_answer_1_and_more"),
        ("accounts", "0007_remove_user_is_email_verified"),
    ]

    operations = []
